'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.1433
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("iPhoneBrowser.itouchBrowser.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  iPhone is connected, not jailbroken に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String1() As String
            Get
                Return ResourceManager.GetString("String1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Copy Dock Image に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String10() As String
            Get
                Return ResourceManager.GetString("String10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Copy Icon for に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String11() As String
            Get
                Return ResourceManager.GetString("String11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Copying &apos; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String12() As String
            Get
                Return ResourceManager.GetString("String12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Backing up &apos; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String13() As String
            Get
                Return ResourceManager.GetString("String13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  iPhoneBrowser に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String14() As String
            Get
                Return ResourceManager.GetString("String14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  An error has occured during load.  Error text: に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String15() As String
            Get
                Return ResourceManager.GetString("String15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  .  The program will now exit, sorry. Please report this online. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String16() As String
            Get
                Return ResourceManager.GetString("String16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Are you sure you wish to delete the &apos;{0}&apos; file? (A backup copy will automatically be created) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String17() As String
            Get
                Return ResourceManager.GetString("String17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Select a file to replace {0} with ... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String18() As String
            Get
                Return ResourceManager.GetString("String18", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Are you sure you want to remove {0}? に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String19() As String
            Get
                Return ResourceManager.GetString("String19", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  iPhone is NOT connected, please check your connections! に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String2() As String
            Get
                Return ResourceManager.GetString("String2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  [For your safety, all contents will be backed up.] に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String20() As String
            Get
                Return ResourceManager.GetString("String20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Please enter the name of the new folder you wish to create.  The new path of this folder will be:{0}&lt;new folder&gt;, and the name is case-sensitive! に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String21() As String
            Get
                Return ResourceManager.GetString("String21", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  No spaces, slashes or other special characters are allowed in the folder name. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String22() As String
            Get
                Return ResourceManager.GetString("String22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  The path &apos;{0}&apos; already exists. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String23() As String
            Get
                Return ResourceManager.GetString("String23", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  iPhone is connected and jailbroken に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String3() As String
            Get
                Return ResourceManager.GetString("String3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Refreshing folders for {0}... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String4() As String
            Get
                Return ResourceManager.GetString("String4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Loading Files for {0}... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String5() As String
            Get
                Return ResourceManager.GetString("String5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Files on your iPhone in the &apos;{0}&apos; Directory に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String6() As String
            Get
                Return ResourceManager.GetString("String6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  This function goes through all of your backup files and attempts to remove the duplicates to save space. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String7() As String
            Get
                Return ResourceManager.GetString("String7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  You really don&apos;t have to do this, it is better to have more backups then less...but press ok if you&apos;ve got a lot of backups. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String8() As String
            Get
                Return ResourceManager.GetString("String8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Copy Wallpaper Image に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String9() As String
            Get
                Return ResourceManager.GetString("String9", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property warning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
