'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.3603
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("iPhoneBrowser.itouchBrowser.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property AddOnIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AddOnIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AudioCD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AudioCD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AudioFile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AudioFile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BuilderDialog_movedown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BuilderDialog_movedown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Camera() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Camera", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CLSDFOLD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CLSDFOLD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dbs() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("dbs", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property document() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Folder_Back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Folder_Back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FullScreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FullScreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Network_Internet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Network_Internet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NewMessageHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewMessageHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OPENFOLD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OPENFOLD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PageUpHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PageUpHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PrimaryKeyHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PrimaryKeyHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SecurityLock() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("SecurityLock", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property SecurityLock1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SecurityLock1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  iPhone is connected, not jailbroken (no afc2 service found) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String1() As String
            Get
                Return ResourceManager.GetString("String1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Copy Dock Image に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String10() As String
            Get
                Return ResourceManager.GetString("String10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Copy Icon for に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String11() As String
            Get
                Return ResourceManager.GetString("String11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Copying &apos; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String12() As String
            Get
                Return ResourceManager.GetString("String12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Backing up &apos; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String13() As String
            Get
                Return ResourceManager.GetString("String13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  itouchBrowser に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String14() As String
            Get
                Return ResourceManager.GetString("String14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  An error has occured during load.  Error text: に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String15() As String
            Get
                Return ResourceManager.GetString("String15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  .
        '''
        '''Service of iTunes may not have started. Please check being installed correctly. 
        '''The program will now exit, sorry. Please report this online. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String16() As String
            Get
                Return ResourceManager.GetString("String16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Are you sure you wish to delete the &apos;{0}&apos; file? (A backup copy will automatically be created) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String17() As String
            Get
                Return ResourceManager.GetString("String17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Select a file to replace {0} with ... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String18() As String
            Get
                Return ResourceManager.GetString("String18", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Are you sure you want to remove {0}? に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String19() As String
            Get
                Return ResourceManager.GetString("String19", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  iPhone is NOT connected, please check your connections! に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String2() As String
            Get
                Return ResourceManager.GetString("String2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  [For your safety, all contents will be backed up.] に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String20() As String
            Get
                Return ResourceManager.GetString("String20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Please enter the name of the new folder you wish to create.  The new path of this folder will be:{0}&lt;new folder&gt;, and the name is case-sensitive! に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String21() As String
            Get
                Return ResourceManager.GetString("String21", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  No slashes or other special characters are allowed in the folder name. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String22() As String
            Get
                Return ResourceManager.GetString("String22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  The path &apos;{0}&apos; already exists. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String23() As String
            Get
                Return ResourceManager.GetString("String23", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Only one file can be replaced at a time に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String24() As String
            Get
                Return ResourceManager.GetString("String24", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Error: The program could not find the path &apos;{0}&apos; on your iPhone.  Creation appeared to be successful に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String25() As String
            Get
                Return ResourceManager.GetString("String25", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  &quot;Error: The program could not create the path &apos;{0}&apos; on your iPhone.  Have you successfully used jailbreak? に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String26() As String
            Get
                Return ResourceManager.GetString("String26", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Do you want to create {0}? に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String27() As String
            Get
                Return ResourceManager.GetString("String27", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Loading file  に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String28() As String
            Get
                Return ResourceManager.GetString("String28", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  File details for &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String29() As String
            Get
                Return ResourceManager.GetString("String29", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  iPhone is connected and jailbroken に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String3() As String
            Get
                Return ResourceManager.GetString("String3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  The program was unable to copy {0} from the iPhone.  Sorry, try again! に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String30() As String
            Get
                Return ResourceManager.GetString("String30", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Size に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String31() As String
            Get
                Return ResourceManager.GetString("String31", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Black に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String32() As String
            Get
                Return ResourceManager.GetString("String32", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Gray に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String33() As String
            Get
                Return ResourceManager.GetString("String33", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  White に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String34() As String
            Get
                Return ResourceManager.GetString("String34", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Path does not exist. A reboot this application may be necessity. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String35() As String
            Get
                Return ResourceManager.GetString("String35", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Latest に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String36() As String
            Get
                Return ResourceManager.GetString("String36", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Same に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String37() As String
            Get
                Return ResourceManager.GetString("String37", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Different に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String38() As String
            Get
                Return ResourceManager.GetString("String38", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Completed successfully. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String39() As String
            Get
                Return ResourceManager.GetString("String39", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Refreshing folders for {0}... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String4() As String
            Get
                Return ResourceManager.GetString("String4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Comitted file count : に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String40() As String
            Get
                Return ResourceManager.GetString("String40", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  It became possible to manage a backup file. In order to manage a backup file, a database needs to be built. Does it reconstruct? に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String41() As String
            Get
                Return ResourceManager.GetString("String41", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  This function can be performed even from a menu. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String42() As String
            Get
                Return ResourceManager.GetString("String42", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Although the &apos;{0}&apos; is specified as a backup directory, it cannot access there.
        '''Is a backup place changed? に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String43() As String
            Get
                Return ResourceManager.GetString("String43", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Backup is compared and the file of the same contents is deleted. It may take several minutes, when there are many files. Please wait for a while. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String44() As String
            Get
                Return ResourceManager.GetString("String44", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Select the destination folder for saving に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String45() As String
            Get
                Return ResourceManager.GetString("String45", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  You didn&apos;t change the default name, I am pretty sure you don&apos;t want a &apos;NewFolder&apos; folder name... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String46() As String
            Get
                Return ResourceManager.GetString("String46", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Can not use rename to move a folder に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String47() As String
            Get
                Return ResourceManager.GetString("String47", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Enter new folder name: に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String48() As String
            Get
                Return ResourceManager.GetString("String48", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Backup Dir. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String49() As String
            Get
                Return ResourceManager.GetString("String49", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Loading Files for {0}... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String5() As String
            Get
                Return ResourceManager.GetString("String5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Song Name に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String50() As String
            Get
                Return ResourceManager.GetString("String50", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Album に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String51() As String
            Get
                Return ResourceManager.GetString("String51", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Track Number に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String52() As String
            Get
                Return ResourceManager.GetString("String52", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Genre に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String53() As String
            Get
                Return ResourceManager.GetString("String53", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Type に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String54() As String
            Get
                Return ResourceManager.GetString("String54", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Comment に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String55() As String
            Get
                Return ResourceManager.GetString("String55", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  My Music に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String56() As String
            Get
                Return ResourceManager.GetString("String56", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Desctop に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String57() As String
            Get
                Return ResourceManager.GetString("String57", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  My Computer に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String58() As String
            Get
                Return ResourceManager.GetString("String58", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  My Documents に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String59() As String
            Get
                Return ResourceManager.GetString("String59", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Files on your iPhone in the &apos;{0}&apos; Directory に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String6() As String
            Get
                Return ResourceManager.GetString("String6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Please choose the directory to write out. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String60() As String
            Get
                Return ResourceManager.GetString("String60", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Please choose the directory which creates SSH key pair. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String61() As String
            Get
                Return ResourceManager.GetString("String61", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Backup {0} folder... に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String62() As String
            Get
                Return ResourceManager.GetString("String62", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  This function goes through all of your backup files and attempts to remove the duplicates to save space. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String7() As String
            Get
                Return ResourceManager.GetString("String7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  You really don&apos;t have to do this, it is better to have more backups then less...but press ok if you&apos;ve got a lot of backups. に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String8() As String
            Get
                Return ResourceManager.GetString("String8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Copy Wallpaper Image に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property String9() As String
            Get
                Return ResourceManager.GetString("String9", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property VideoCamera() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VideoCamera", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property VPN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VPN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property warning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property window() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("window", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property XPfolder_closed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("XPfolder_closed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property XPfolder_Open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("XPfolder_Open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
